package com.kadziela.games.bridge.model.enumeration;

public enum ScoreLineItem 
{
	CONTRACT_NT_FIRST (40),
	CONTRACT_NT_SUBSEQUENT (30),
	CONTRACT_MAJOR (30),
	CONTRACT_MINOR (20),
	CONTRACT_NT_FIRST_DOUBLED (80),
	CONTRACT_NT_SUBSEQUENT_DOUBLED (60),
	CONTRACT_MAJOR_DOUBLED (60),
	CONTRACT_MINOR_DOUBLED (40),
	CONTRACT_NT_FIRST_REDOUBLED (160),
	CONTRACT_NT_SUBSEQUENT_REDOUBLED (120),
	CONTRACT_MAJOR_REDOUBLED (120),
	CONTRACT_MINOR_REDOUBLED (80),
	OVERTRICK_NT_OR_MAJOR (30),
	OVERTRICK_MINOR (20),
	OVERTRICK_DOUBLED_NV (100),
	OVERTRICK_DOUBLED_V (200),
	OVERTRICK_REDOUBLED_NV (200),
	OVERTRICK_REDOUBLED_V (400),
	SLAM_SMALL_NV (500),
	SLAM_SMALL_V (750),
	SLAM_GRAND_NV (1000),
	SLAM_GRAND_V (1500),
	DOUBLE_BONUS (50),
	REDOUBLE_BONUS (100),
	UNDERTRICK_NV (50),
	UNDERTRICK_V (100),
	UNDERTRICK_NV_DOUBLED_FIRST (100),
	UNDERTRICK_NV_REDOUBLED_FIRST (200),
	UNDERTRICK_NV_DOUBLED_SECOND_THIRD (200),
	UNDERTRICK_NV_REDOUBLED_SECOND_THIRD (400),
	UNDERTRICK_NV_DOUBLED_FOURTH_OR_MORE (300),
	UNDERTRICK_NV_REDOUBLED_FOURTH_OR_MORE (600),
	UNDERTRICK_V_DOUBLED_FIRST (200),
	UNDERTRICK_V_REDOUBLED_FIRST (400),
	UNDERTRICK_V_DOUBLED_SECOND_OR_MORE (300),
	UNDERTRICK_V_REDOUBLED_SECOND_OR_MORE (600),
	RUBER_FAST (700),
	RUBER_SLOW (500),
	HONORS_HIGH (150),
	HONORS (100);

	public final int points;
	
	private ScoreLineItem(int pts) {points = pts;}
}